### ISSUE TITLE
Provide an example of using the slurm backend with stimela

### ISSUE THREAD

**Issue by landmanbester** [africalim/resources#4]
I've had a couple of requests asking for this. Just keeping track of it here so I don't forget

**Comment by Victoria-Samboco** [comment]
An example of how to set slurm backend to be able to run on ilifu. Under ```opts``` in your main recipe  set the backend to ```slurm``` and you can also add the ```srun_opts``` to define ```time```, ```mem``` for  memory , ```cpus-per-task```, etc.



``` 
opts:
   backend:
     slurm:
       enable: true
       srun_opts:
         time: 1-8
         mem: 100GB
         cpus-per-task: 1
 ```
